// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bolnica_back.Model;

namespace bolnica_back.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211112233242_ThirdMigration")]
    partial class ThirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("bolnica_back.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("EMail")
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Jmbg")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Svetosavska 11",
                            EMail = "pp@gmail.com",
                            Gender = 0,
                            Jmbg = "123123123",
                            Name = "Petar",
                            Password = "123",
                            PhoneNumber = "023857197",
                            Role = 0,
                            Surname = "Petrovic",
                            Username = "pera"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Dositejea 2",
                            EMail = "mm@gmail.com",
                            Gender = 0,
                            Jmbg = "321321321",
                            Name = "Mika",
                            Password = "123",
                            PhoneNumber = "023857555",
                            Role = 0,
                            Surname = "Mikic",
                            Username = "mika"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
